spring:
  thymeleaf:
    cache: false
    prefix: file:///etc/thymeleaf/templates/
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    protocol: smtp
#    username: GMAIL USER NAME
#    password: GMAIL PASSWORD
#    tls: true
#    properties.mail.smtp:
#        auth: true
#        starttls.enable: true
#        ssl.trust: smtp.gmail.com
